Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://localhost:3000"
  root: "/home/iross/projects/survey-server/modules"
  aws_access: "AKIAJL2ZFXJGAVKR5GGQ"
  aws_secret: "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"

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "http://survey.skybluetrades.net"
  port: 3001
  <<: *defaults
