Default: &defaults
  database: survey-server.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: survey-server_test.sqlite3
  <<: *defaults

Staging:
  database: survey-server_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: survey-server_production.sqlite3
  poolsize: 100
  <<: *defaults
